dbtlearn:
  outputs:
    dev:
      account: # Fill in the Snowflake Account Name here (someting like: yczmxn-dk96978)
      database: AIRBNB
      password: dbtPassword123
      role: transform
      schema: dev
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
    databricks:
      type: databricks
      catalog: shell_prep
      host: XXXXX.cloud.databricks.com
      http_path: /sql/1.0/warehouses/XXXXX
      schema: airbnb
      threads: 4
      auth_type: oauth
  
  target: databricks
  